### ISSUE TITLE
How do you use timeOffset in contact()->recent?

### ISSUE THREAD

**Issue by bickart** [fungku/hubspot-php#12]
I asked HubSpot for the most recent contacts about 20 minutes ago. I would like to know how to properly get any changes that have occurred in the last 20 minutes?

**Comment by fungku** [comment]
I haven't used this one yet, but I would do some test runs with a `timeOffset` something like:

```php
$timeOffset = (int) (strtotime("20 minutes ago") * 1000); // timestamp in milliseconds for hubspot
```

**Comment by fungku** [comment]
I haven't used this one yet, but I would do some test runs with a `timeOffset` something like:

```php
// timestamp in milliseconds
$timeOffset = (int) (strtotime("20 minutes ago") * 1000);
```

I may be missing something, unfortunately, HubSpot Docs don't make it clear to me how vidOffset and timeOffset are related.

**Comment by fungku** [comment]
I haven't used this one yet, but I would do some test runs with a `timeOffset` something like:

```php
// timestamp in milliseconds
$timeOffset = (int) (strtotime("20 minutes ago") * 1000);

$contacts = $hubspot->contacts()->recent([
    'properties' => [
        'timeOffset' => $timeOffset,
]);
```

I may be missing something, unfortunately, HubSpot Docs don't make it clear to me how vidOffset and timeOffset are related other than they are "Used in conjunction."

**Comment by fungku** [comment]
@bickart  Did you figure this one out yet?

**Comment by bickart** [comment]
In short no. My use case was to get updated contacts since the last time I requested. So if I request for updates every 1/2 hour. I only want to know what changed in the last 1/2 hour. I don't care about anything prior to that. It doesn't seen that HubSpot wants to cooperate with me. HubSpot will give you the most recent updates even if was 2 hours ago. So I use the time updated (don't remember the exact field) in each contact returned to determine if I have an update or skip.

**Comment by fungku** [comment]
Yeah, I honestly can't figure out what hubspot is doing with the timeOffset here. It does not seem to work as a specific cut-off like you'd expect like with vid-offset...

https://api.hubapi.com/contacts/v1/lists/recently_updated/contacts/recent?hapikey=demo&count=100&timeOffset=1432148571000

**Comment by fungku** [comment]
The **timeOffset** parameter is apparently the "end" time and the contacts are displayed in reverse chronological order from then.

Seems kind of silly to me, but I will add a method that does what I think the `recent()` method should *actually* do.
