### ISSUE TITLE
Case Sensitive File Names

### ISSUE THREAD

**Issue by bickart** [fungku/hubspot-php#14]
In the file HubSpotService.php there is a function

```
 protected function getApiClassName($name)
 {
        return 'Fungku\\HubSpot\\Api\\' . ucfirst($name);
 }
```

This incorrectly returns the filename; for example contactproperties returns as Contactproperties where it should return as ContactProperties or the Api/ContactProperties.php needs to be changed to Api/Contactproperties.php

Any ideas on how to resolve this issue?

**Comment by fungku** [comment]
The `$name` argument should be a string that matches the functions listed here: https://github.com/fungku/hubspot-php/blob/master/src/HubSpotService.php#L13

so for example `method contactProperties()` would mean the `$name` is `'contactProperties'` and then the output of the `getApiClassName` method would be `'ContactProperties'`.

**Comment by fungku** [comment]
```php
$hubspot = Fungku\HubSpot\HubSpotService::make('api-key');

$contactProperties = $hubspot->contactProperties();
```

should give you an instance of `Fungku\HubSpot\ContactProperties`

**Comment by bickart** [comment]
Got it thanks; I'll update my code to properly reference the correct names

**Comment by fungku** [comment]
:)

**Comment by bickart** [comment]
Have you tried Enhancv?It gives you real-time suggestions to help you
create the perfect resume so you can land your dream job. 
<https://enhancv.com?utm_source=growth&utm_campaign=invite-friends&utm_medium=email&utm_content=email-logo> =
Have you tried Enhancv? =

Hey, I’m using Enhancv to create a resume that stands out and land my
dream job.

By joining me, you will help me get $3 off the Enhancv Pro account and earn
credit for yourself. There’s also a 14-day free trial, so you can check
it out right away: https://app.enhancv.com/invite/57b29f8bb1aab4110038b3b1

- Jeff Bickart

 www.enhancv.com
<https://enhancv.com?utm_source=growth&utm_campaign=invite-friends&utm_medium=email>

  Copyright © 2017 Enhancv, All rights reserved.

 This is a one time email which has been prompted by Jeff Bickart. We will
not contact you further, unless you signup to the platform.
