### ISSUE TITLE
Add example file

### ISSUE THREAD

**Issue by louiswalch** [fungku/hubspot-php#16]
Would it be possible to add a working example file. I am kind of new to PHP name spaces, and not quite sure how to start this off. It seems like if I try including the HubSpotService file then it isn't auto-including any other referenced files (e.g. BlogPosts). I am sure I'm just making a namespace noob mistake.

**Comment by fungku** [comment]
I plan to add more documentation in the future. In the meantime, try this:

```php
<?php

# index.php

require "vendor/autoload.php"

use Fungku\HubSpot\HubSpotService;

$hubspot = HubSpotService::make('demo');

$contacts = $hubspot->contacts()->all(['count' => 10]);

foreach ($contacts as $contact) {
    echo $contact['properties']['email']['value'];
}

```
