### ISSUE TITLE
v2 API

### ISSUE THREAD

**Issue by bickart** [fungku/hubspot-php#17]
Are you planning on updating the endpoints to the v2 API?

**Comment by fungku** [comment]
Which endpoints are v2 now?

The docs for the endpoints I use (mainly contacts) still show v1

**Comment by bickart** [comment]
I've been working with contactProperties today which are all now v2

**Comment by fungku** [comment]
The endpoints that were v2 at the time of writing are done as v2.

e.g. https://github.com/fungku/hubspot-php/blob/master/src/Api/Forms.php#L15


Any others I see, that switch over, I will switch as well.

**Comment by bickart** [comment]
great thanks

**Comment by fungku** [comment]
:thumbsup:

**Comment by bickart** [comment]
Hey, I’m using Enhancv to create a resume that stands out and land my
dream job.

By joining me, you will help me get $3 off the Enhancv Pro account and earn
credit for yourself. There’s also a 14-day free trial, so you can check
it out right away: https://app.enhancv.com/invite/57b29f8bb1aab4110038b3b1

- Jeff Bickart
