### ISSUE TITLE
Is there a mechanism to support Oauth

### ISSUE THREAD

**Issue by bickart** [fungku/hubspot-php#3]
The HubSpot API allows for two means of authentication, OAuth and API keys.

API keys are great for rapid prototyping, but for security and commercial use, all integrations should strive to use OAuth. 

http://developers.hubspot.com/docs/overview

**Comment by fungku** [comment]
I just added a commit that will allow you to make the service with an oauth token instead of an api key.

```php
$hubspot = Fungku\HubSpot\HubSpotService::make('api-key');
```

`composer require fungku/hubspot-php: dev-master@dev`

if you want to test it.

7d74f00b1884a84417c13b4da3baed97fb565764

**Comment by bickart** [comment]
Great! I'll give a try tomorrow or the next day
