### ISSUE TITLE
Allow to pass ArrayAccess as parameter

### ISSUE THREAD

**Issue by nediam** [fungku/hubspot-php#4]
Hi, what do you think about allowing to pass ArrayAccess into parameters for methods that uses `query`?
For example here: https://github.com/fungku/hubspot-php/blob/master/src/Api/ContactLists.php#L139
It allows me to use `\GuzzleHttp\Query` and set custom aggregator on it.

**Comment by fungku** [comment]
That's not a bad idea.

**Comment by fungku** [comment]
So, I might remove the array typehint to allow this...

Thoughts?

**Comment by nediam** [comment]
Yes, but I think it should be checked in method body if ists array or instance of ArrayAccess, I can do it but for 2 weeks.

**Comment by fungku** [comment]
Does this 331c3ab2177598dc6761d7ed358d19fbeb8419b4 work for you?

**Comment by nediam** [comment]
Yep, I think its ok :) Thanks!
