### ISSUE TITLE
https://github.com/fungku/hubspot-php#paginate-through-all-contacts

### ISSUE THREAD

**Issue by bickart** [fungku/hubspot-php#6]
In your example https://github.com/fungku/hubspot-php#paginate-through-all-contacts; you are using properties when you should be using property

if you replace with the correct parameter; then the firstname and lastname are not returned. Can you determine the cause of this issue?

**Comment by fungku** [comment]
running this script

```php
<?php

require "vendor/autoload.php";

use Fungku\HubSpot\HubSpotService;

$hubspot = HubSpotService::make('demo');

$collection = $hubspot->contacts()->all([
        'count'      => 10,
        'properties' => 'firstname, lastname',
        'vidOffset'  => 123456,
]);

foreach ($collection['contacts'] as $contact) {
    $firstname = $contact['properties']['firstname']['value'];
    $lastname = $contact['properties']['lastname']['value'];
    echo "Name: {$firstname} {$lastname}" . PHP_EOL;
}
```

gives me this output:

![output](http://i.snag.gy/gKLib.jpg)

**Comment by fungku** [comment]
Sorry, you are correct. If you correct it to property you can only include one property, and adding additional ones breaks it.

I will look at it more closely tonight.

**Comment by fungku** [comment]
That should work now.
