### ISSUE TITLE
Exception thrown when contact isn't found

### ISSUE THREAD

**Issue by ianhawes** [fungku/hubspot-php#9]
Is there a better way to do this? 

Right now if a contact isn't found a ClientException from Guzzle is thrown.

**Comment by fungku** [comment]
Yes, we should probably return a json response with an error message.

**Comment by fungku** [comment]
Example json response

```json
{
   "error":{
      "status": 404,
      "message": "Not Found",
      "url": "https:\/\/api.hubapi.com\/contacts\/v1\/contact\/vid\/123456\/profile?hapikey=demo"
   }
}
```

**Comment by fungku** [comment]
Sorry, I am tired... newborn at home :P 

Is this better? e250b8380b3eb6618100a66a413da2cddd2f04aa
